name: Sync config/locales to repo2

on:
  push:
    branches:
      - main
    paths:
      - 'config/locales/**'  # Only trigger when these files change

jobs:
  sync-to-repo2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo1
        uses: actions/checkout@v4

      - name: Prepare sync folder
        run: |
          mkdir sync-folder
          cp -r config/locales/* sync-folder/

      - name: Clone repo2 and sync
        env:
          PAT: ${{ secrets.REPO2_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Clone repo2 outside of the current repo to avoid nested git repo issues
          cd ..
          git clone https://$PAT@github.com/katpadi/test-repo2.git repo2
          cd repo2

          # Create or switch to sync branch
          git checkout -B sync-locales-from-repo1

          # Clean all files except .git
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +

          # Copy synced files from repo1
          cp -r ../repo1/sync-folder/* .

          # Commit and push if there are changes
          if [[ $(git status --porcelain) ]]; then
            git add .
            git commit -m "Sync locales from repo1"
            git push --force origin sync-locales-from-repo1
          else
            echo "No changes to commit"
          fi

      - name: Create PR on repo2
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.REPO2_PAT }}
          commit-message: Sync locales from repo1
          branch: sync-locales-from-repo1
          base: main
          title: "Sync locales from repo1"
          body: |
            This PR syncs `config/locales/` from repo1 (main branch).
